### PR TITLE
Fix connection string

### LINKED ISSUE #31: Special characters in connection string do not work as advertised
Example: password='my;password'
This currently fails.

### PR DESCRIPTION
**Pull request by agalakhov**
This closes #31.

### CODE REVIEW

File: tiberius/src/lib.rs [hunk 1]
```diff
@@ -640,44 +641,68 @@ impl<'a> ToConnectEndpoint<Box<BoxableIo>, DynamicConnectionTarget> for &'a str
...
         while !input.is_empty() {
-            let key_end = input.bytes().position(|x| x == b'=');
-            let (key, key_end) = match key_end {
-                None => return Err(TdsError::Conversion("connection string expected key. expected `=` never found".into())),
-                Some(key_end) => ((&input[..key_end]).to_lowercase(), key_end)
+            // (MSDN) The basic format of a connection string includes a series of keyword/value
+            // pairs separated by semicolons. The equal sign (=) connects each keyword and its value.
+            let key = {
+                let mut t = input.splitn(2, '=');
+                let key = t.next().unwrap();
```
Comment (steffengy) [inline tiberius/src/lib.rs]: Don't panic there, return an error.

File: tiberius/src/lib.rs [hunk 2]
```diff
@@ -640,44 +641,68 @@ impl<'a> ToConnectEndpoint<Box<BoxableIo>, DynamicConnectionTarget> for &'a str
...
-                        },
-                        b'\\' if next+1 < input.len() && input.as_bytes()[next+1] == b'\'' => {
-                            val.push('\'');
-                            input = &input[1..]; // <=> &[next+2..] effectively
-                        },
-                        b'\\' => val.push('\\'),
-                        _ => unreachable!()
+                    let mut t = input.splitn(3, quote_char);
+                    t.next().unwrap(); // skip first quote character
+                    value.push_str(t.next().unwrap());
```
Comment (steffengy) [inline tiberius/src/lib.rs]: This might also panic, if the input only consists of a single quote character. Don't panic here.

File: tiberius/src/lib.rs (hunk 1 above)
Comment (agalakhov) [reply tiberius/src/lib.rs]: No. If it panics here, it is a bug in this code and not a wrong input. The `splitn()` iterator always returns a valid first value (maybe an empty string), so the first `next()` never returns `None` regardless of the value of `input`.

Comment (steffengy) [reply tiberius/src/lib.rs]: Oh right for this one, not sure if this shows a helpful message for malformed keys, but should be fine.

File: tiberius/src/lib.rs (hunk 2 above)
Comment (agalakhov) [reply tiberius/src/lib.rs]: Same here. The first character must be `quote_char` regardless of the input (guaranteed by the `if`s), then at least two first iterator values are always valid. If it panics here, it means a bug somewhere in `if` statements below. There is no user input string that could cause failure here.

Comment (agalakhov) [reply tiberius/src/lib.rs]: An example demonstrating how it works:
```
let mut t = "".splitn(2, ",");                                                                  
t.next().unwrap();                                                                              
assert_eq!(t.next(), None);                                                                                                                                                      
                                                                                             
let mut t = ",".splitn(3, ",");                                                                 
t.next().unwrap();                                                                              
t.next().unwrap();                                                                              
assert_eq!(t.next(), None);                                                                     
```

Comment (steffengy) [reply tiberius/src/lib.rs]: Okay, wasn't clear to me from the docs, thanks.
I don't quite the unwraps (since it isn't immediately obvious that those are "safe"),
but atleast it works.

**Comment by steffengy** [comment]
Thanks!

File: tiberius/src/lib.rs (hunk 2 above)
Comment (agalakhov) [reply tiberius/src/lib.rs]: In our company we tend to write `.expect("Bug: expected something blablabla")` in such places, so that, if a crash is reported, the developer sees the cause immediately.

Thank you!
